version: '{branch}.{build}'
clone_depth: 3
build: off
test: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
services:
  - iis
  # We can't start more than one MSSQL instance to avoid conflicts on TCP port 1433. The only workaround to test a check
  # against multiple versions is letting the test code to start/stop the corresponding services so that they run one at
  # a time. See https://www.appveyor.com/docs/services-databases/ for details.
  - mssql2008r2sp2

environment:
  PYTHON2: C:\Python27-x64
  PYTHON3: C:\Python36-x64

  matrix:
    - CHECK: datadog_checks_base
    - CHECK: active_directory
    - CHECK: aspdotnet
    - CHECK: dotnetclr
    - CHECK: exchange_server
    - CHECK: iis
    - CHECK: pdh_check
    - CHECK: sqlserver
    - CHECK: win32_event_log
    - CHECK: windows_service
    - CHECK: wmi_check

init:
  # Add Python 3 to PATH
  - set PATH=%PYTHON3%;%PYTHON3%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

  # Add Python 2 to PATH before Python 3
  - set PATH=%PYTHON2%;%PYTHON2%\Scripts;%PATH%
  - python -c "import sys; print(sys.version)"

install:
  - python -m pip install --upgrade --disable-pip-version-check pip virtualenv codecov
  - pip uninstall -y docker-py
  - pip install .\datadog_checks_dev[cli]
  - ddev config set core .

test_script:
  - ddev test %CHECK%

# Uncomment the following to enable RDP connection into the builder and debug a build
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

for:
  -
    branches:
      only:
        - head

    environment:
      PYTHON2: C:\Python27-x64
      PYTHON3: C:\Python36-x64

    test_script:
      # Only test any of these that have changed for pull requests
      - ddev test --changed datadog_checks_base active_directory aspdotnet dotnetclr exchange_server iis pdh_check sqlserver win32_event_log windows_service wmi_check
